name: go_router_paths
description: Helps define paths for `go_router` and other navigation packages. Remove those hard coded strings!
version: 0.3.0
repository: https://github.com/mrgnhnt96/go_router_paths
homepage: https://github.com/mrgnhnt96/go_router_paths
issue_tracker: https://github.com/mrgnhnt96/go_router_paths/issues
topics:
  - go-router
  - router
  - paths
  - navigation

environment:
  sdk: ">=2.18.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0

scripts: derry.yaml
